apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.services.port }}
    protocol: TCP
    targetPort: {{ .Values.services.port }}
  selector:
    app: techtrends
  type: {{ .Values.services.type }}
